services:
  auto-power:
    build:
      context: .
      dockerfile: Dockerfile
    image: auto_power:latest
    container_name: auto_power
    ports:
      - "9548:8000"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
